### ISSUE TITLE
app.json init crashes

### ISSUE THREAD

**Issue by TravelingTechGuy** [app-json/app.json#22]
OSX Yosemite/Node 0.12.2/app.json@1.2.1

```bash
$ app.json init
/opt/local/lib/node_modules/app.json/lib/heroku.js:153
        return config[key].url.match(/git@heroku\.com:(.*)\.git/)[1]
                                                                 ^
TypeError: Cannot read property '1' of null
    at /opt/local/lib/node_modules/app.json/lib/heroku.js:153:66
    at Array.map (native)
    at EventEmitter.module.exports.Heroku.deriveAppNamesFromLocalGitConfig (/opt/local/lib/node_modules/app.json/lib/heroku.js:152:8)
    at Command.<anonymous> (/opt/local/lib/node_modules/app.json/bin/cli:60:14)
    at Command.listener (/opt/local/lib/node_modules/app.json/node_modules/commander/index.js:301:8)
    at Command.emit (events.js:110:17)
    at Command.parseArgs (/opt/local/lib/node_modules/app.json/node_modules/commander/index.js:610:12)
    at Command.parse (/opt/local/lib/node_modules/app.json/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/opt/local/lib/node_modules/app.json/bin/cli:234:9)
    at Module._compile (module.js:460:26)
```

**Comment by denyago** [comment]
+1

**Comment by denyago** [comment]
Crashes on origins like `url = https://git.heroku.com/foo.git`
Works on origins like `url = git@heroku.com:foo.git`

**Comment by TravelingTechGuy** [comment]
Well, I see no one touched this repo in months, so I assume no fix is coming.

**Comment by zeke** [comment]
Hi @TravelingTechGuy and @denyago. I worked on this project just before leaving Heroku, and it has not been maintained by anyone at the company since I left last fall. Unfortunately I don't have the free time to actively develop it any more, but I will happily review pull requests, and will hand off the project to anyone who wishes to take it over.

**Comment by TravelingTechGuy** [comment]
Hi @zeke - sounds good. I'll see if I can dive into this.

**Comment by TravelingTechGuy** [comment]
Ok, now this module can't even be installed (on Windows, Node 0.12.5). 

Heroku: please mark this repo "Defunct" and remove the module from the NPM repository.

**Comment by josegonzalez** [comment]
@denyago thanks for the hint, was relatively easy to fix!

@zeke thanks for your initial work on this repository, it is very much appreciated :) Hope you can still approve my pr/make a release to github :)

**Comment by etewiah** [comment]
Just to clarify, the remote url can be changed with the "git remote set-url" command.

In my case it was:

`git remote set-url heroku git@heroku.com:propertywebbuilder.git`

**Comment by onemonster** [comment]
https://git.heroku.com/my_app.git
Mine was in this format so I fixed it with 
`return config[key].url.match(/git.heroku\.com\/(.*)\.git/)[1])`
pretty easy fix
